### ISSUE TITLE
How to call "await" within "fakeAsync"

### ISSUE THREAD

**Issue by HerrNiklasRaab** [dart-lang/fake_async#29]
Hello, 

how can I await a Future within a fakeAsync zone?

When I do this, than the callback doesn't get executed:
``` dart
    fakeAsync((fakeAsync) async {
          await someAsyncMethod();
    });
```

When I await the `fakeAsync`, it never returns. 
``` dart
    await fakeAsync((fakeAsync) async {
          await someAsyncMethod();
    });
```

Any idea?

Best,

Niklas

**Comment by mtwichel** [comment]
I'm also facing a similar issue. Is this possible to do?

**Comment by wujek-srujek** [comment]
I would also be interested. As soon as I use `await` with this lib my test hangs or doesn't do anything after it, depending on what and how I write. There is curiously very little documentation about this package so no clear tips. I took a look at the tests but there is not a single `await` to be found there. But it must be possible, Flutter tests use it, e.g. `pump` uses `elapse` internally and it is possible (actually, I think we must) `await` on `pump`s.

**Comment by jeduden** [comment]
I go this to work as follows:

```
    fakeAsync((async) {
      someAsyncMethod(); // just launch the asynchronous function call without awaiting it.
      async.elapse(new Duration(seconds: 0)); // call elapse to execute the async function call.
    });
```

**Comment by matuella** [comment]
I think this package has a couple of pertinent unaddressed issues (and lack of examples are one of them). Nonetheless, using [Danny's answer](https://stackoverflow.com/a/62676919/8558606) has solved almost all of my issues with `fake_async` hanging on `Future`s. Not even close to ideal, but it works.

I also tried digging on how one would "fix" this, and found this [interesting discussion](https://github.com/flutter/flutter/issues/75155#issuecomment-773435635), meaning that I couldn't find an alternative way to the above, although good, non-ideal solution.

**Comment by natebosch** [comment]
We don't have a single suggested pattern for this yet. Closing this issue in favor of https://github.com/dart-lang/fake_async/issues/24 which has some discussion of potential designs.
